### ISSUE TITLE
Potential Copyright Issue with Included Image

### ISSUE THREAD

**Issue by f4ah6o** [calvin-mcd/travaulta#1]
Thank you for sharing your great work. However, I have a concern.

Including a copyrighted movie scene in an open-source project is problematic, even if it's a meme:

* **Copyright infringement**: Unauthorized use violates copyright.
* **License conflict**: It contradicts open-source license terms.
* **Legal risks**: Contributors may face legal issues.

I recommend using copyright-free or original content instead.

For reference: [Confused Travolta Meme](https://knowyourmeme.com/memes/confused-travolta)

![image](https://github.com/calvin-mcd/travaulta/assets/14793610/02b0f71c-df6c-434f-9bd2-687d52fe900f)

**Comment by calvin-mcd** [comment]
Thanks for pointing that out. I have decided to change license and use one that is explicitly non-commercial. I hope that resolves the Issue.
